codeplaysoftware/standards-proposals

- asynchronous-data-flow/sycl-2.2/03_interacting_with_data_on_the_host.md
Since there can currently only be one kernel per command group, there are certain expectations that need to be met and it would be difficult to meet them if host tasks were allowed alongside kernel invocations in the same command group. So until the limit of one kernel per group is lifted, this should should be disallowed, i.e. even though multiple host tasks per command group are allowed, also using a kernel invocation in the same command group should not be.
> Disallow mixing host tasks with kernel invocations

- asynchronous-data-flow/sycl-2.2/03_interacting_with_data_on_the_host.md
* Added `update_to_device` API call, along with an example
* Changed the order of arguments for `update_from_device` so that it follows `std::memcpy` (first argument destination, second one source)
* Made the type of the accessor passed to these functions more verbose
* Restrictions on the access mode and access target for the accessor passed to these functions
> Changes for updating data to/from device

- README.md
- placeholder_accessors/index.md
Initial public commit of a proposal for an accessor type that is not
bound to a specific command group, aimed at SYCL 2.2.
> Placeholder Accessor proposal for SYCL 2.2

- tied-buffer/index.md
- tied-buffer/sycl-2.2/buffer-properties.cpp
- tied-buffer/sycl-2.2/buffer-tags.md
- tied-buffer/sycl-2.2/tied-buffer.md
The buffer tags are now buffer properties.
Buffer properties can take parameters, which simplifies the interface
and enables adding extensions.
The tied-buffer proposal has been refurbished to work with properties
instead of derived classes.
> Updated buffer properties proposal

- asynchronous-data-flow/sycl-2.2/03_interacting_with_data_on_the_host.md
In the documentation for [`clEnqueueFillBuffer` ](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueFillBuffer.html), the pattern size needs to be one of 1, 2, 4, 8, 16, 32, 64, 128. It makes sense to have this restriction for the `fill` function as well because enabling it in the general case would be very inefficient.
Also fixed an accessor name typo.
> Fill pattern size restrictions

- affinity/cpp-20/d0796r1.md
Listing 1 in d0796r1 had incorrect syntax.
Fix the example so readers won't object.
Reword surrounding text for correctness and clarity.
> d0796r1: Fix Listing 1 to have correct syntax

- affinity/cpp-20/d0796r1.md
In d0796r1, fix grammar and wording in "Background Research: State of the Art" section.
> d0796r1: Fix "Background Research..." section

- affinity/cpp-20/d0796r2.md
* Introduce the `this_thread::get_resource` free function for retrieving
the underlying execution resource of the current thread of execution.
* Rename `this_system::resources` to `this_system::get_resources` to be
more consistent with the current standard.
* Correct typos.
> Issue #34: Introduce free function for retrieving a threads resource

- affinity/cpp-20/d0796r2.md
* Make mionor corrections and fixes.
* Add note to the wording of the `bulk_execution_affinity_t` nestested
properties that requires them to adhere to the requirements of
behavioural properties.
* Rephrase text to remove use of high-level and low-level terms as can
be read ambiguously.
* Add straw poll on the execution context design direction.
> P0796r2: Final changes

- affinity/cpp-20/d0796r3.md
* Remove bind() and unbind() functions and the associated wording.
> Issue #64: Remove explicit bind/unbind interface.

- affinity/cpp-20/d0796r3.md
* Replace execution_resource::resources with execution_resource::begin
and execution_resource::end.
* Add execution_resource::size.
* Add execution_resource::operator[].
* Add aliases to execution_resource to support new interface.
* Improve woring for execution resource and system topology.
* Update examples to suppoort change.
* Rename this_system::resources to this_system::discover_topology.
> Issue #50: Make execution_resource iterable.

- README.md
- onchip-memory/index.md
- onchip-memory/sycl-1.2.1/onchip-memory.md
SYCL vendor extension proposal to introduce a property to buffers for allocating on-chip memory.
> CP019: Initial draft of on-chip memory proposal

- interop_task/interop_task.md
This proposal add the possibility for a user to retrieve cl_mem object in a friendly way for SYCL data-flow model.
The proposal adds interop_task member function to the codeplay::handler to schedule the execution of a task on the host.
It provides also a way to retrieve cl_mem object associated to an accessor to allow full interoperability with OpenCL.
> Add proposal for interop_task

- README.md
- affinity/cpp-20/d1436r0.md
- affinity/cpp-20/d1437r0.md
- affinity/cpp-20/dXXX1r0.md
- affinity/index.md
**Changes**
* Replace current motivational example with two new examples: one
showing migration of a pre-allocated container to gain affinity, and one
showing using the bulk_execution_affinity property to bind allocation
and execution locality.
* Introduce the `concurrency_t property`, reflecting that which was
previously available via the `execution_context`.
* Introduce the `execution_locality_intersection_t` property which
returns the maximum concurrency common to two executors.
* Introduce the `memory_locality_intersection_t` property which returns
true if two executors have a common address space.
* Remove sections of background research not relative to high-level
interface.
* Add examples for each of the new properties.
* Update future work section to be more relative to the …
> CP013: Introduce new properties and examples to affinity paper

- README.md
- affinity/cpp-23/d1436r1.md
- affinity/index.md
* Introduce wording to describe when two invocations of `bulk_execute`
are expected to have consistent binding.
* Introduce wording to describe how `bulk_execute` should handle an
execution context failing to provide the guaranteed binding.
* Update the example for `bulk_execution_affinity` to demonstrate how to
use `prefer` and `query`.
* Update the wording of `bulk_execution_affinity.scatter` and
`bulk_execution_affinity.balance` to better describe the expected
binding pattern.
* Add a note about potetial limitations of resource utilization when
using `bulk_execution_affinity`.
> CP013: Wording improvements.

- README.md
- default-constructed-buffers/default-constructed-buffers.md
Default constructible buffers would be a useful addition for generic
code. This proposal adds a zero-argument constructor and functions
for determining whether or not a buffer is usable.
> Add proposal for default-constructible buffers

- affinity/cpp-23/d1436r2.md
**Summary**
* Updates the wording for `bulk_execution_affinity` properties to make them hints rather than guarantees.
* Minor editorial fixes to the wording.
**Todo**
* This pull request removes wording that describes guarantees about consistency between invocations of `bulk_execute`, a further property needs to be introduced to reintroduce this functionality.
> CP013: Make affinity properties hints

- interop_task/interop_task.md
* `get_buffer` renamed to `get_mem`
* Clarified wording on `get_queue` and `get_mem`
* `interop_handle` is passed by value to the lambda instead of reference
> [SYCL] Interop Task R2

- default-constructed-buffers/default-constructed-buffers.md
Feedback has been gathered from internal prototyping and we have used
this to inform the proposal.
> Update default-ctor proposal

- affinity/cpp-23/d1795r1.md
- affinity/index.md
* Add terms of art for system topology, system resource and topology discovery policy.
* Add minimal design for`system_topology`
* Add free function `this_system::discover_topology`.
* Introduce minimal `system_resource` class.
* Introduce free function `traverse_topology` for traversing a
`system_topology` according to a topology traversal policy.
* Update the changelog.
> CP013: Add initial proposal for `this_system::discover_topology`

- README.md
- affinity/cpp-23/d1436r3.md
- affinity/cpp-23/d1795r2.md
- affinity/index.md
* Update links for P1436r2 and P1795r1.
* Create new revisions for D1436r3 and D1795r2.
* Update readme and index.
> Update P1436 and P1795 after Belfast ISO C++ meeting.

- affinity/cpp-23/d1436r3.md
* Rename `bulk_execution_affinity_t::scatter_t` to `bulk_execution_affinity_t::spread_t`.
* Rename `bulk_execution_affinity_t::compact_t` to `bulk_execution_affinity_t::close_t`.
* Refine the wording of the `bulk_execution_affinity_t` properties to clarify the requirements on binding and chunking, based on feedback from SG1.
> Update the wording of the bulk_execution_affinity properties in P1436

- README.md
- host_task/host_task.md
- interop_task/interop_task.md
Previously known as the interop task extension (CP20).
This new iteration of the extension includes both host task and
interop task on the same command group.
It is presented as a vendor extension for SYCL 1.2.1, but includes
direction as to how to integrate with the SYCL Generalization proposal.
> Rev 0.6 of Host Task with interop capabilities

- max_work_item_sizes/max_work_item_sizes.md
Adds a proposal for splitting `max_work_item_sizes` descriptor for `get_info` into dimensionality-dependent queries.
> CP024: Dimensionality-dependent max work-item sizes

- general_property_lists/general_property_lists.md
Adds a proposal for generalizing the use of property lists for all user-constructible SYCL objects.
> CP025: Property list generalization

- affinity/cpp-23/d2155r0.md
- affinity/cpp-23/dXXXXr0.md
- affinity/index.md
Introduce a draft of the ISO C++ paper for proposing an execution policy property for describing the implications of adjacency in bulk algorithms. This paper is a continuation of P1436, taking in feedback from a discussion in SG1 at the Prague ISO C++ meeting.
Note, the motivation section is taken straight from P1436r2 so I plan to update that to refine it before submission. I also plan to add a changelog that will link back to P1436.
> Add P2155r0: Policy property for describing adjacency

- README.md
- auto-require/index.md
1. Allow skipping `require`
2. Define convenience functions
3. Don't allow this on kernel enqueues
> CP28 Automatic placeholder requirements
